language: php

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - cp coverage.xml clover.xml
  - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT
